--- 
- name: Test connect
  hosts: all
  become: yes

  tasks:
  - name: Ping all servers
    ping:

  - name: Check release
    shell: lsb_release -a
    register: result

  - name: print
    debug: 
      var: result