---
# tasks file for deploy_flask_app
- name: Create a network and connect containers
  docker_network:
    name: "{{ docker_network_name }}"

- name: Start 3 load-balanced containers
  docker_container:
    name: "app-{{ item }}"
    recreate: yes
    image: "{{ default_container_image }}"
    networks:
      - name: "{{ docker_network_name }}"
    ports: 
      - "{{ item }}:5000"
  loop:
    - "5000"
    - "5001"
    - "5002"

# - name: Create a network and connect containers
#   docker_network:
#     name: "{{ docker_network_name }}"
#     connected: 
#       - app-{{ item }}
#     appends: yes
#   with_sequence: count=3
