---
# tasks file for deploy_flask_app
- name: Create app container and connect to network
  docker_container:
    name: {{ default_container_name }}{{ container_port }}
    image: {{ default_container_image }}
    state: started
    networks:
      - name: "{{ docker_network_name }}"
    ports: 
      - "{{ container_port }}:5000"