---
# tasks file for deploy_flask_app
- name: Start 3 load-balanced containers
  docker_container:
    name: "container{{ item }}"
    recreate: yes
    image: {{ default_container_image }}
    command: sleep 1d
  with_sequence: count=3