---
# tasks file for deploy_flask_app
- name: Start 3 load-balanced containers
  docker_container:
    name: "container{{ item }}"
    recreate: yes
    image: mustafaevsl/epam-flask-app:latest
    command: sleep 1d
  with_sequence: count=3