---
# tasks file for deploy_nginx_balancer
- name: Create a directory for nginx
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: templates/defaults.conf
    dest: /etc/nginx/conf.d/defaults.conf

- name: Generate config file from jinja
  template: 
    src: config.j2 
    dest: /etc/nginx/conf.d/balancer.conf

- name: Start Nginx load balancer
  docker_container:
    name: "nginxBalancer"
    recreate: yes
    image: "nginx"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    ports: 
      - "80:80"
  
    